### ISSUE TITLE
Podcast 

### ISSUE THREAD

**Issue by blkluv** [nonseodion/Web3-Pods#1]
What is the source of the podcasts minted? Can you contact me on Telegram @hahznft

**Comment by nonseodion** [comment]
They are static. I added the data already to the metadata of the NFTs.

**Comment by hahzterry** [comment]
> They are static. I added the data already to the metadata of the NFTs.

Can you assist me on what contract information needs to be changed?

**Comment by nonseodion** [comment]
It's the metadata that needs to be changed. Here's the sample metadata:

```
{
  "name": "Inside the Lazerpay Shutdown: A Conversation with Njoku Emmanuel",
  "image": "https://ipfs.io/ipfs/bafybeibaa4by4vygw4teyw5j5kn6pwpukqblxbg2yeoaxhdyqgflzmhpgm/cryptoatscale.webp",
  "description": "Lazerpay was shutdown, that’s not news. But what does Njoku Emmanuel have to say to the critics?",
  "attributes": {
    "episode-link": "https://pod.link/cryptoatscale/episode/51ab443ac865fac0169e31bd8f7dbdc3",
    "podcast-name": "Crypto@Scale"
  }
}
```
